// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_Xal3O1JKqAMtIXC8HEkg4UZGgUQRn8',
    appId: '1:223135447310:web:644cf1a3afbb94846eff5f',
    messagingSenderId: '223135447310',
    projectId: 'parametrageschool',
    authDomain: 'parametrageschool.firebaseapp.com',
    storageBucket: 'parametrageschool.firebasestorage.app',
    measurementId: 'G-4FJHH81S44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNyDEu4qKx9SUIHH17mJ0AN58dQbtkt4',
    appId: '1:223135447310:android:0324b02c29f738696eff5f',
    messagingSenderId: '223135447310',
    projectId: 'parametrageschool',
    storageBucket: 'parametrageschool.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_Xal3O1JKqAMtIXC8HEkg4UZGgUQRn8',
    appId: '1:223135447310:web:d3dbcb7b8dec095d6eff5f',
    messagingSenderId: '223135447310',
    projectId: 'parametrageschool',
    authDomain: 'parametrageschool.firebaseapp.com',
    storageBucket: 'parametrageschool.firebasestorage.app',
    measurementId: 'G-5QVL4MVX0P',
  );
}
